start /wait python.exe Conv_2d_Zone3.py
start /wait python.exe Conv_2d_Zone4.py
start /wait python.exe Conv_2d_Zone5.py
start /wait python.exe Conv_2d_Zone7.py
start /wait python.exe Conv_2d_Zone9.py
start /wait python.exe Conv_2d_Zone10.py
start /wait python.exe Conv_2d_Zone12.py
start /wait python.exe Conv_2d_Zone14.py
start /wait python.exe Conv_2d_Zone16.py
start /wait python.exe Conv_2d_Zone17.py